### ISSUE TITLE
Fix CONFIG_THERMO

### ISSUE THREAD

**Issue by SecMeant** [SecMeant/pico-furnace#16]
Thanks, @husxk for spotting this.

CONFIG_THERMO is broken. The `Ktype` and `pt100` preprocessor comparisons doesn't work, because:
https://gcc.gnu.org/onlinedocs/gcc-3.0.1/cpp_4.html

> Identifiers that are not macros, which are all considered to be the number zero. This allows you to write #if MACRO instead of #ifdef MACRO, if you know that MACRO, when defined, will always have a nonzero value. Function-like macros used without their function call parentheses are also treated as zero.

**Comment by SecMeant** [comment]
@kornelu123

**Comment by SecMeant** [comment]
@husxk will fix this

**Comment by kornelu123** [comment]
should we close this ?

**Comment by SecMeant** [comment]
Yup. Merged this manually [eee23eed22694b27c45967570fa64d76e089fc91](https://github.com/SecMeant/pico-furnace/commit/eee23eed22694b27c45967570fa64d76e089fc91)
